### ISSUE TITLE
验证码下载失败无法登录

### ISSUE THREAD

**Issue by zhmushan** [VinceMockghy/zucc_xk_ZhengFang#3]
![image](https://user-images.githubusercontent.com/24505451/84274155-18d55400-ab62-11ea-8c19-1387b4dc2c7d.png)
```ps
#Begin to login
##GET login page succeed!
###Identify checkCode
Traceback (most recent call last):
  File ".\main.py", line 66, in <module>
    account.login()
  File "C:\Users\zhbnh\Desktop\zucc_xk_ZhengFang\LOGIN.py", line 76, in login
    self.__get_check_code_ocr()
  File "C:\Users\zhbnh\Desktop\zucc_xk_ZhengFang\LOGIN.py", line 61, in __get_check_code_ocr
    self.POSTDate['txtSecretCode'] = OCR_CODE.run(img_dir, dir_now=img_dir)
  File "C:\Users\zhbnh\Desktop\zucc_xk_ZhengFang\OCR_CODE.py", line 107, in run
    image = Image.open(image_path + "code.gif")
  File "C:\Users\zhbnh\scoop\apps\anaconda3\current\lib\site-packages\PIL\Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\zhbnh\\Desktop\\zucc_xk_ZhengFang/code.gif'
```

**Comment by VinceMockghy** [comment]
确认过了，我这里也不行了，刚刚去选课网看了下是选课网给验证码加了个SaveKey。目前正在解决...

**Comment by VinceMockghy** [comment]
验证码部分改好了，可以git pull最新的代码

**Comment by zhmushan** [comment]
thx, 可以了

**Comment by zhmushan** [comment]
![image](https://user-images.githubusercontent.com/24505451/84585972-b7ee9a00-ae47-11ea-99d2-57fb7994026f.png)
终于抢到英语课, 来还愿啦, 谢谢作者= =
